apiVersion: template.openshift.io/v1
kind: Template
labels:
  puppetboard: master
message: |-
  The following service(s) have been created in your project: ${PUPPETBOARD_SERVICE_NAME}.

     PuppetDB Host: ${PUPPETDB_HOST}
     PuppetDB Port: ${PUPPETDB_PORT}
        Secret Key: ${PUPPETBOARD_SECRET_KEY}
  Puppetboard Port: ${PUPPETBOARD_PORT}

  For more information about using this template, including OpenShift considerations, see https://github.com/sclorg/mysql-container/blob/master/8.0/root/usr/share/container-scripts/mysql/README.md.
metadata:
  annotations:
    description: Description
    iconClass: icon-puppetboard
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"template.openshift.io/v1","kind":"Template","labels":{"puppetboard":"master"},"message":"The following service(s) have been created in your project: ${DATABASE_SERVICE_NAME}.\n\n   PuppetDB Host: ${PUPPETDB_HOST}\n   PuppetDB Port: ${PUPPETDB_PORT}\n      Secret Key: ${PUPPETBOARD_SECRET_KEY}\nPuppetboard Port: ${PUPPETBOARD_PORT}\n\nFor more information about using this template, including OpenShift considerations, see https://github.com/sclorg/mysql-container/blob/master/8.0/root/usr/share/container-scripts/mysql/README.md.","metadata":{"annotations":{"description":"Description","iconClass":"icon-puppetboard","tags":"database,nosql"},"creationTimestamp":"2024-03-13T12:16:49Z","name":"puppetboard-template","namespace":"schoneckerb-junk","resourceVersion":"1850559501","uid":"b2229e3a-68e3-48bc-8b82-cd4cd933eddb"},"objects":[{"apiVersion":"v1","kind":"Pod","metadata":{"name":"puppetboard-master"},"spec":{"containers":[{"env":[{"name":"REDIS_PASSWORD","value":"${REDIS_PASSWORD}"}],"image":"dockerfile/puppetboard","name":"master","ports":[{"containerPort":6379,"protocol":"TCP"}]}]}}],"parameters":[{"description":"The name of the OpenShift Service exposed for Puppetboard.","displayName":"Puppetboard Service Name","name":"PUPPETBOARD_SERVICE_NAME","required":true,"value":"puppetboard"},{"description":"Remote server where PuppetDB is running.","displayName":"PuppetDB Remote Server","from":"[a-zA-Z0-9]","generate":"expression","name":"PUPPETDB_HOST","required":true,"value":"puppetdb"},{"description":"Secret Key for the Puppetboard.","displayName":"Puppetboard Secret Key","from":"[a-zA-Z0-9]","generate":"expression","name":"PUPPETBOARD_SECRET_KEY","required":true,"value":"Secr3t_K3y"},{"description":"The name of the OpenShift Service exposed for Puppetboard.","displayName":"Puppetboard Service Name","name":"PUPPETBOARD_SERVICE_NAME","required":true,"value":"puppetboard"},{"description":"The port on which the Puppetboard server offers up the web interface.","displayName":"Puppetboard Port","name":"PUPPETBOARD_PORT","required":true,"value":"1024"},{"description":"The remote port on the PuppetDB server where Postgresql is listening.","displayName":"Remote PuppetDB port","name":"PUPPETDB_PORT","required":true,"value":"8080"},{"description":"The name of the OpenShift Service exposed for Puppetboard.","displayName":"Puppetboard Service Name","name":"PUPPETBOARD_SERVICE_NAME","required":true,"value":"puppetboard"},{"description":"The URL of the repository with the Puppetboard application code.","displayName":"Puppetboard Repository URL","name":"PUPPETBOARD_SOURCE_REPOSITORY_URL","required":true,"value":"https://github.com/voxpupuli/puppet-puppetboard.git"},{"description":"The branch name, tag or other ref of the PUPPETBOARD_SOURCE_REPOSITORY_URL.","displayName":"Puppetboard Repository Ref","name":"PUPPETBOARD_SOURCE_REPOISOTRY_REF","required":true,"value":"master"}]}
    tags: database,nosql
  name: puppetboard-template
  namespace: schoneckerb-junk
objects:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${PUPPETBOARD_SERVICE_NAME}
      app.kubernetes.io/component: ${PUPPETBOARD_SERVICE_NAME}
      app.kubernetes.io/instance: ${PUPPETBOARD_SERVICE_NAME}
    name: ${PUPPETBOARD_SERVICE_NAME}
    namespace: schoneckerb-junk
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: "${PUPPETBOARD_SERVICE_NAME}:latest"
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/voxpupuli/puppetboard.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: python:3.12-alpine
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: QWAtBu3UnE5j8bHL8L1N
      type: GitHub
    - generic:
        secret: q2Wf0ftyxh41hmxPnvNh
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
- apiVersion: build.openshift.io/v1
  kind: Build
  metadata:
    labels:
      app: ${PUPPETBOARD_SERVICE_NAME}
      app.kubernetes.io/component: ${PUPPETBOARD_SERVICE_NAME}
      app.kubernetes.io/instance: ${PUPPETBOARD_SERVICE_NAME}
      buildconfig: ${PUPPETBOARD_SERVICE_NAME}
      openshift.io/build-config.name: ${PUPPETBOARD_SERVICE_NAME}
      openshift.io/build.start-policy: Serial
    name: ${PUPPETBOARD_SERVICE_NAME}
    namespace: schoneckerb-junk
  spec:
    nodeSelector: null
    output:
      pushSecret:
        name: builder-dockercfg-q4wxs
      to:
        kind: ImageStreamTag
        name: "${PUPPETBOARD_SERVICE_NAME}:latest"
    serviceAccount: builder
    source:
      git:
        uri: https://github.com/voxpupuli/puppetboard.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: python@sha256:849ed6079c9f797ca9c1b7d6aea1c00aea3ac35110cbd0d6003f15950017ea8d
      type: Docker
    triggeredBy:
    - message: Build configuration change



- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: ${PUPPETBOARD_SERVICE_NAME}
      app.kubernetes.io/component: ${PUPPETBOARD_SERVICE_NAME}
      app.kubernetes.io/instance: ${PUPPETBOARD_SERVICE_NAME}
    name: ${PUPPETBOARD_SERVICE_NAME}
    namespace: schoneckerb-junk
    ipFamilyPolicy: SingleStack
  spec:
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: "${PUPPETBOARD_PORT}-tcp"
      port: 80
      protocol: TCP
      targetPort: ${{PUPPETBOARD_PORT}}
    selector:
      deployment: ${PUPPETBOARD_SERVICE_NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: ${PUPPETBOARD_SERVICE_NAME}
      app.kubernetes.io/component: puppetboard
      app.kubernetes.io/instance: puppetboard
    name: ${PUPPETBOARD_SERVICE_NAME}
    namespace: schoneckerb-junk
  spec:
    #progressDeadlineSeconds: 600
    #revisionHistoryLimit: 10
    selector:
      matchLabels:
        deployment: ${PUPPETBOARD_SERVICE_NAME}
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        labels:
          deployment: ${PUPPETBOARD_SERVICE_NAME}
      spec:
        containers:
        - env:
          - name: PUPPETDB_HOST
            value: ${PUPPETDB_HOST}
          - name: PUPPETDB_PORT
            value: ${PUPPETDB_PORT}
          - name: PUPPETBOARD_PORT
            value: ${PUPPETBOARD_PORT}
          - name: SECRET_KEY
            value: ${PUPPETBOARD_SECRET_KEY}
          image: ghcr.io/voxpupuli/puppetboard@sha256:c9202d6eb90b298d7233b9c4d26f7656e68d58abc93221e2aee75fcb68a69926
          imagePullPolicy: IfNotPresent
          name: ${PUPPETBOARD_SERVICE_NAME}
          ports:
          - containerPort: ${{PUPPETBOARD_PORT}}
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
# - apiVersion: v1
#   kind: Pod
#   metadata:
#     name: puppetboard-master
#   spec:
#     containers:
#     - env:
#       - name: REDIS_PASSWORD
#         value: ${REDIS_PASSWORD}
#       image: dockerfile/puppetboard
#       name: master
#       ports:
#       - containerPort: 6379
#         protocol: TCP
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ${PUPPETBOARD_SERVICE_NAME}
      app.kubernetes.io/component: ${PUPPETBOARD_SERVICE_NAME}
      app.kubernetes.io/instance: ${PUPPETBOARD_SERVICE_NAME}
    name: ${PUPPETBOARD_SERVICE_NAME}
    namespace: schoneckerb-junk
  spec:
    host: "${PUPPETBOARD_SERVICE_NAME}-schoneckerb-junk.apps.non-prod.nfii.com"
    port:
      targetPort: "${PUPPETBOARD_PORT}-tcp"
    to:
      kind: Service
      name: ${PUPPETBOARD_SERVICE_NAME}
      weight: 100
    wildcardPolicy: None




parameters:
- description: The name of the OpenShift Service exposed for Puppetboard.
  displayName: Puppetboard Service Name
  name: PUPPETBOARD_SERVICE_NAME
  required: true
  value: puppetboard
- description: Remote server where PuppetDB is running.
  displayName: PuppetDB Remote Server
  from: '[a-zA-Z0-9]'
  generate: expression
  name: PUPPETDB_HOST
  required: true
  value: puppetdb
- description: Secret Key for the Puppetboard.
  displayName: Puppetboard Secret Key
  from: '[a-zA-Z0-9]'
  generate: expression
  name: PUPPETBOARD_SECRET_KEY
  required: true
  value: Secr3t_K3y
- description: The name of the OpenShift Service exposed for Puppetboard.
  displayName: Puppetboard Service Name
  name: PUPPETBOARD_SERVICE_NAME
  required: true
  value: puppetboard
- description: The port on which the Puppetboard server offers up the web interface.
  displayName: Puppetboard Port
  name: PUPPETBOARD_PORT
  required: true
  value: "1024"
  type: integer
- description: The remote port on the PuppetDB server where Postgresql is listening.
  displayName: Remote PuppetDB port
  name: PUPPETDB_PORT
  required: true
  type: integer
  value: "8080"
- description: The name of the OpenShift Service exposed for Puppetboard.
  displayName: Puppetboard Service Name
  name: PUPPETBOARD_SERVICE_NAME
  required: true
  value: puppetboard
- description: The URL of the repository with the Puppetboard application code.
  displayName: Puppetboard Repository URL
  name: PUPPETBOARD_SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/voxpupuli/puppet-puppetboard.git
- description: The branch name, tag or other ref of the PUPPETBOARD_SOURCE_REPOSITORY_URL.
  displayName: Puppetboard Repository Ref
  name: PUPPETBOARD_SOURCE_REPOISOTRY_REF
  required: true
  value: master
